# Generated by Django 3.1 on 2021-06-20 13:41

from django.db import migrations, models
import src.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True, validators=[src.validators.bleach_validator]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100, validators=[src.validators.bleach_validator]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=100, validators=[src.validators.bleach_validator]),
        ),
    ]
