# Generated by Django 3.1 on 2021-06-21 13:42

from django.db import migrations, models
import src.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210620_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=src.validators.upload_image_path),
        ),
    ]
