# Generated by Django 3.1 on 2021-06-20 13:41

from django.db import migrations, models
import src.validators


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=250, validators=[src.validators.bleach_validator]),
        ),
    ]
