# Generated by Django 3.1 on 2021-06-23 13:08

from django.db import migrations, models
import src.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210620_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, validators=[src.validators.bleach_validator]),
        ),
    ]
