# Generated by Django 3.1 on 2021-06-20 13:41

from django.db import migrations, models
import src.validators


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210618_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True, validators=[src.validators.bleach_validator]),
        ),
    ]
