# Generated by Django 3.1 on 2021-06-23 13:08

from django.db import migrations, models
import src.validators


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210621_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to=src.validators.category_upload_image_path),
        ),
    ]
